{
 "title": "user Server Logs [purrtopia]",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "purrtopia 指令使用統計", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "指令使用次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (name) (count_over_time({container=\"purrtopia-discord-bot\"} |= \"[USAGE]\" | regexp \"name=(?P<name>[^ ]+)\" | name=~\"冰雪季|代售查詢|代售登記|代售總覽|代購查詢|代購登記\" [$__interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "使用者使用次數",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (user) (count_over_time({container=\"purrtopia-discord-bot\"} |= \"[USAGE]\" | regexp \"user=(?P<user>[^ ]+)\" [$__interval]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "purrtopia",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"purrtopia-discord-bot\"}"
    }
   ]
  }
 ]
}